# config.toml file for temp-mail
[app]
name = "temp-mail" # Name of the application
version = "0.1.0" # Version of the application

[server]
host = "localhost" # Host to listen
port = 3000 # Port to listen
secret = 31 # Secret for webhook
prefork = false # Enable preforking for better performance

[domains]
aliases = ["pageton.org", "devrio.org"] # Domains to postfix

[database]
path = "mail.db" # Path to database file
